# Generated by Django 4.0.6 on 2023-04-14 19:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_profile_chosen_room_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("film_work_name", models.CharField(default="", max_length=120)),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "db_table": "cinema_together_film",
            },
        ),
    ]
