# Generated by Django 4.0.6 on 2023-04-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_work_url_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
